name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-roamlinks-plugin
      - run: pip install mkdocs-mermaid2-plugin
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Install packages
        run: npm install
        working-directory: ./docs/slides/test
      - name: Check packages
        run: ls -la
        working-directory: ./docs/slides/test
      - name: Build packages
        working-directory: ./docs/slides/test
        run: npm run build --if-present
      - run: mkdocs gh-deploy --force
